photomarket/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from django.conf.urls.static import static
from django.conf import settings

from dashboard.views import DashboardView
from checkout.views import CheckoutTestView, CheckoutAjaxView

urlpatterns = [
    url(r'^$', DashboardView.as_view(), name="dashboard"),
    url(r'^admin/', admin.site.urls),
    url(r'^test/$', CheckoutTestView.as_view(), name='test'),
    url(r'^checkout/$', CheckoutAjaxView.as_view(), name='checkout'),

    url(r'^products/',include('products.urls',namespace='products')),
    url(r'^seller/', include("sellers.urls", namespace='sellers')),
    url(r'^tags/',include('tags.urls',namespace='tags')),
]

if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.conf.urls import url
from django.contrib import admin

from .views import (detail_view, detail_slug_view, create_view, update_view,
                    ProductListView, ProductDetailView,
                    ProductDownloadView,
                    ProductCreateView, ProductUpdateView)

urlpatterns = [
    url(r'^update/(?P<pk>\d+)/$', ProductUpdateView.as_view(), name='update_view'),
    url(r'^update/(?P<slug>[\w-]+)/$', ProductUpdateView.as_view(), name='update_slug_view'),
    url(r'^create/$', ProductCreateView.as_view(), name='create_view'),
    url(r'^list/$', ProductListView.as_view(), name='list_view'),
    url(r'^(?P<pk>\d+)/download/$', ProductDownloadView.as_view(), name='download'),
    url(r'^(?P<slug>[\w-]+)/download/$', ProductDownloadView.as_view(), name='download_slug'),
    url(r'^(?P<pk>\d+)/$', ProductDetailView.as_view(), name='detail_view'),
    url(r'^(?P<slug>[\w-]+)/$', ProductDetailView.as_view(), name='detail_slug_view'),
    # url(r'^create/$', TweetCreateView.as_view(), name='create'),
    # url(r'^(?P<pk>\d+)/$', TweetDetailView.as_view(), name='detail'),
    # url(r'^(?P<pk>\d+)/update/$', TweetUpdateView.as_view(), name='update'),
    # url(r'^(?P<pk>\d+)/delete/$', TweetDeleteView.as_view(), name='delete'),
]

tags/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from .views import (
        TagDetailView,
        TagListView,
        )

urlpatterns = [
    url(r'^$', TagListView.as_view(), name='list'),
    url(r'^(?P<slug>[\w-]+)/$', TagDetailView.as_view(), name='detail'),
]

products/models.py
from django.db import models
from django.conf import settings
from django.core.files.storage import FileSystemStorage
from django.db.models.signals import pre_save, post_save
from django.utils.text import slugify
from django.urls import reverse
# Create your models here.

from sellers.models import SellerAccount



def download_media_location(instance, filename):
	return "%s/%s" %(instance.slug, filename)

class Product(models.Model):
	seller = models.ForeignKey(SellerAccount,default=3)
	user = models.ForeignKey(settings.AUTH_USER_MODEL)
	managers = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="managers_products", blank=True)
	media = models.ImageField(null=True,blank=True,upload_to=download_media_location,
                    storage=FileSystemStorage(location=settings.PROTECTED_ROOT))
	title = models.CharField(null=False, blank=False, max_length=300)
	slug = models.SlugField(blank=True,unique=True)
	description = models.CharField(null=True, blank=True, max_length=300)
	price = models.DecimalField(max_digits=100,decimal_places=2,default=0.00)
	sale_active = models.BooleanField(default=False)
	sale_price = models.DecimalField(max_digits=100,decimal_places=2,default=0.00)


	def __str__(self):
		return str(self.title)

	def get_absolute_url(self):
		return reverse('products:detail_slug_view', kwargs={'slug':self.slug})

	def get_edit_url(self):
		view_name = "sellers:product_edit"
		return reverse(view_name, kwargs={"pk": self.id})

	def get_download(self):
		view_name = "products:download_slug"
		url = reverse(view_name, kwargs={"slug": self.slug})
		return url

	@property
	def get_price(self):
		if self.sale_price and self.sale_active:
			return self.sale_price
		return self.price

	def get_html_price(self):
		price = self.get_price
		if price == self.sale_price:
			return "<p><span>%s</span> <span style='color:red;text-decoration:line-through;'>%s</span></p>" %(self.sale_price, self.price)
		else:
			return "<p>%s</p>" %(self.price)



def create_slug(instance, new_slug=None):
	slug = slugify(instance.title)
	if new_slug is not None:
		slug = new_slug
	qs = Product.objects.filter(slug=slug)
	exists = qs.exists()
	if exists:
		new_slug = "%s-%s" %(slug, qs.first().id)
		return create_slug(instance, new_slug=new_slug)
	return slug


def product_pre_save_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = create_slug(instance)

pre_save.connect(product_pre_save_receiver, Product)


def thumbnail_location(instance, filename):
	return "%s/%s" %(instance.product.slug, filename)

THUMB_CHOICES = (
	("hd", "HD"),
	("sd", "SD"),
	("micro", "Micro"),
)

class Thumbnail(models.Model):
	product = models.ForeignKey(Product) #instance.product.title
	type = models.CharField(max_length=20, choices=THUMB_CHOICES, default='hd')
	height = models.CharField(max_length=20, null=True, blank=True)
	width = models.CharField(max_length=20, null=True, blank=True)
	media = models.ImageField(
		width_field = "width",
		height_field = "height",
		blank=True,
		null=True,
		upload_to=thumbnail_location)

	def __str__(self): # __str__(self):
		return str(self.media.path)


import os
import shutil
from PIL import Image
import random

from django.core.files import File


def create_new_thumb(media_path, instance, owner_slug, max_length, max_width):
		filename = os.path.basename(media_path)
		thumb = Image.open(media_path)
		size = (max_length, max_width)
		thumb.thumbnail(size, Image.ANTIALIAS)
		temp_loc = "%s/%s/tmp" %(settings.MEDIA_ROOT, owner_slug)
		if not os.path.exists(temp_loc):
			os.makedirs(temp_loc)
		temp_file_path = os.path.join(temp_loc, filename)
		if os.path.exists(temp_file_path):
			temp_path = os.path.join(temp_loc, "%s" %(random.random()))
			os.makedirs(temp_path)
			temp_file_path = os.path.join(temp_path, filename)

		temp_image = open(temp_file_path, "w")
		thumb.save(temp_image)
		thumb_data = open(temp_file_path, "rb")

		thumb_file = File(thumb_data)
		instance.media.save(filename, thumb_file)
		shutil.rmtree(temp_loc, ignore_errors=True)
		return True


def product_post_save_receiver(sender, instance, created, *args, **kwargs):
	if instance.media:
		hd, hd_created = Thumbnail.objects.get_or_create(product=instance, type='hd')
		sd, sd_created = Thumbnail.objects.get_or_create(product=instance, type='sd')
		micro, micro_created = Thumbnail.objects.get_or_create(product=instance, type='micro')

		hd_max = (500, 500)
		sd_max = (350, 350)
		micro_max = (150, 150)

		media_path = instance.media.path
		owner_slug = instance.slug
		if hd_created:
			create_new_thumb(media_path, hd, owner_slug, hd_max[0], hd_max[1])
			# filename = os.path.basename(instance.media.path)
			# thumb = Image.open(instance.media.path)
			# thumb.thumbnail(hd_max, Image.ANTIALIAS)
			# temp_loc = "%s/%s/tmp" %(settings.MEDIA_ROOT, instance.slug)
			# if not os.path.exists(temp_loc):
			# 	os.makedirs(temp_loc)
			# temp_file_path = os.path.join(temp_loc, filename)
			# if os.path.exists(temp_file_path):
			# 	temp_path = os.path.join(temp_loc, "%s" %(random.random()))
			# 	os.makedirs(temp_path)
			# 	temp_file_path = os.path.join(temp_path, filename)

			# temp_image = open(temp_file_path, "w")
			# thumb.save(temp_image)
			# thumb_data = open(temp_file_path, "r")

			# thumb_file = File(thumb_data)
			# hd.media.save(filename, thumb_file)

		if sd_created:
			create_new_thumb(media_path, sd, owner_slug, sd_max[0], sd_max[1])

		if micro_created:
			create_new_thumb(media_path, micro, owner_slug, micro_max[0], micro_max[1])








post_save.connect(product_post_save_receiver, sender=Product)




class MyProducts(models.Model):
	user = models.OneToOneField(settings.AUTH_USER_MODEL)
	products = models.ManyToManyField(Product, blank=True)

	def __unicode__(self):
		return str(self.products.count())

















	# class  Mata:
	# 	ordering = ['-tmiestamp']

products/forms.py
from django import forms

from .models import Product

from django.utils.text import slugify

PUBLICH_CHOICES = (
    ('publish', 'Publish'),
    ('draft', 'Draft'),
)

class ProductAddForm(forms.Form):
    title = forms.CharField(widget=forms.TextInput(
        attrs={
            'class':"my-class",
            'placeholder':"Title"
        }
    ))
    description = forms.CharField(widget=forms.Textarea(
        attrs={
            'class':'my-class',
            'placeholder': "Description"
        }
    ))
    price = forms.DecimalField()
    publish = forms.ChoiceField(widget=forms.RadioSelect,choices=PUBLICH_CHOICES)


    def clean_price(self):
        price = self.cleaned_data.get('price')
        if price < 0.00:
            raise forms.ValidationError("Price shouldn't be less than 0")

        return price



class ProductModelForm(forms.ModelForm):
	tags = forms.CharField(label='Related tags', required=False)
	publish = forms.ChoiceField(widget=forms.RadioSelect, choices=PUBLICH_CHOICES, required=False)
	# description = forms.CharField(widget=forms.Textarea(
	# 		attrs={
	# 			"class": "my-custom-class",
	# 			"placeholder": "Description",
	# 			"some-attr": "this",
	# 		}
	# ))
	class Meta:
		model = Product
		fields = [
			"title",
			"description",
			"price",
		]
		widgets = {
			"description": forms.Textarea(
					attrs={
						"placeholder": "New Description"
					}
				),
			"title": forms.TextInput(
				attrs= {
					"placeholder": "Title"
				}
			)
		}

	def clean(self, *args, **kwargs):
		cleaned_data = super(ProductModelForm, self).clean(*args, **kwargs)
		# title = cleaned_data.get("title")
		# slug = slugify(title)
		# qs = Product.objects.filter(slug=slug).exists()
		# if qs:
		# 	raise forms.ValidationError("Title is taken, new title is needed. Please try again.")
		return cleaned_data

	def clean_price(self):
		price = self.cleaned_data.get("price")
		if price <= 1.00:
			raise forms.ValidationError("Price must be greater than $1.00")

		else:
			return price

	def clean_title(self):
		title = self.cleaned_data.get("title")
		if len(title) > 3:
			return title
		else:
			raise forms.ValidationError("Title must be greater than 3 characters long.")

products/views.py
import os;
from mimetypes import guess_type
from django.shortcuts import render, get_object_or_404
from django.http import Http404, HttpResponse

from django.conf import settings
from wsgiref.util import FileWrapper

from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView

from .models import Product
from django.db.models import Q
from tags.models import Tag
from analytics.models import TagView

from .forms import ProductAddForm, ProductModelForm

from photomarket.mixins import MultiSlugMixin, SubmitBtnMixin, LoginRequiredMixin

from .mixins import ProductManagerMixin
# Create your views here.


from sellers.mixins import SellerAccountMixin


class ProductListView(ListView):
	model = Product
	#template_name = "products/list_view.html"

	def get_queryset(self, *args, **kwargs):
		qs = super(ProductListView, self).get_queryset(**kwargs)
		query = self.request.GET.get("q")
		if query:
			qs = qs.filter(
					Q(title__icontains=query)|
					Q(description__icontains=query)
				).order_by("title")
		return qs


class ProductDetailView(MultiSlugMixin, DetailView):
	model = Product


	def get_context_data(self, *args, **kwargs):
		context = super(ProductDetailView, self).get_context_data(*args, **kwargs)
		obj = self.get_object()
		tags = obj.tag_set.all()
		# rating_avg = obj.productrating_set.aggregate(Avg("rating"), Count("rating"))
		# context["rating_avg"] = rating_avg
		if self.request.user.is_authenticated():
			# rating_obj = ProductRating.objects.filter(user=self.request.user, product=obj)
			# if rating_obj.exists():
			# 	context['my_rating'] = rating_obj.first().rating
			for tag in tags:
				new_view = TagView.objects.add_count(self.request.user, tag)
		return context


class ProductDownloadView(MultiSlugMixin, DetailView):
	model = Product

	def get(self, request, *args, **kwargs):
		obj = self.get_object()
		if obj in request.user.myproducts.products.all():
			filepath = os.path.join(settings.PROTECTED_ROOT, obj.media.path)
			guessed_type = guess_type(filepath)[0]
			wrapper = FileWrapper(open(filepath,'rb'))
			mimetype = 'application/force-download'
			if guessed_type:
				mimetype = guessed_type
				response = HttpResponse(wrapper, content_type=mimetype)

			if not request.GET.get("preview"):
				response["Content-Disposition"] = "attachment; filename=%s" %(obj.media.name)

			response["X-SendFile"] = str(obj.media.name)
			return response
		else:
			raise Http404




class ProductCreateView(LoginRequiredMixin, SubmitBtnMixin, CreateView):
	model = Product
	template_name = "products/form.html"
	form_class = ProductModelForm
	#success_url = "/products/list"
	submit_btn = "Add Product"

	def form_valid(self, form):
		user = self.request.user
		form.instance.user = user
		valid_data = super(ProductCreateView, self).form_valid(form)
		form.instance.managers.add(user)
		tags = form.cleaned_data.get("tags")
		if tags:
			tags_list = tags.split(",")
			for tag in tags_list:
				if not tag == " ":
					new_tag = Tag.objects.get_or_create(title=str(tag).strip())[0]
					new_tag.products.add(form.instance)
		return valid_data


class ProductUpdateView(ProductManagerMixin, SubmitBtnMixin, MultiSlugMixin, UpdateView):
	model = Product
	template_name = "products/form.html"
	form_class = ProductModelForm
	success_url = "/products/list"
	submit_btn = "Update Product"

	def get_initial(self):
		initial = super(ProductUpdateView,self).get_initial()
		tags = self.get_object().tag_set.all()
		initial["tags"] = ", ".join([x.title for x in tags])
		"""
		tag_list = []
		for x in tags:
			tag_list.append(x.title)
		"""
		return initial

	def form_valid(self, form):
		valid_data = super(ProductUpdateView, self).form_valid(form)
		tags = form.cleaned_data.get("tags")
		obj = self.get_object()
		obj.tag_set.clear()
		if tags:
			tags_list = tags.split(",")

			for tag in tags_list:
				if not tag == " ":
					new_tag = Tag.objects.get_or_create(title=str(tag).strip())[0]
					new_tag.products.add(self.get_object())
		return valid_data


def create_view(request):
	print("form here")
	form = ProductAddForm(request.POST or None)
	if form.is_valid():
		print("form valid")
		data = form.cleaned_data
		title = data.get('title')
		desc = data.get('description')
		price = data.get('price')
		prod = Product()
		prod.title = title
		prod.description = desc
		prod.price = price
		prod.save()
	context = {
		'form': form
	}
	return render(request,'products/create_view.html',context)


def update_view(request, pk=None):
	product = get_object_or_404(Product, pk=pk)
	form = ProductModelForm(request.POST or None, instance=product)
	if form.is_valid():
		instance = form.save(commit=False)
		#instance.sale_price = instance.price
		instance.save()
	template = "products/update_view.html"
	context = {
		"object": product,
		"form": form,
		"submit_btn": "Update Product"
		}
	return render(request, template, context)

def detail_view(request, pk=None):
	product = get_object_or_404(Product, id=pk)
	if product is not None:
		context = {
			'object':product
		}
		return render(request,'products/detail_view.html',context)
	else:
		raise Http404

def detail_slug_view(request, slug=None):
	product = get_object_or_404(Product, slug=slug)
	if product is not None:
		context = {
			'object':product
		}
		return render(request,'products/detail_view.html',context)
	else:
		raise Http404


def list_view(request):
	return render(request,'products/list_view.html',{})



class SellerProductListView(SellerAccountMixin, ListView):
	model = Product
	template_name = "sellers/product_list_view.html"

	def get_queryset(self, *args, **kwargs):
		qs = super(SellerProductListView, self).get_queryset(**kwargs)
		qs = qs.filter(seller=self.get_account())
		query = self.request.GET.get("q")
		if query:
			qs = qs.filter(
					Q(title__icontains=query)|
					Q(description__icontains=query)
				).order_by("title")
		return qs

templates/products/create_view.html
{% extends 'base.html' %}

{% block content %}
<form class="" action="" method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit" name="button">Submit</button>
</form>

{% endblock content %}

templates/products/detail_view.html
{% extends "base.html" %}

{% block content %}
{% if object.media %}
  <a href="{{object.get_download}}">download</a>
{% endif %}
<h3>{{ object.title }}</h3>
{% endblock content%}

templates/products/form.html
{% extends "base.html" %}


{% block content %}

{% include "products/form_include.html" with form=form submit_btn=submit_btn %}


{% endblock content %}

templates/products/form_include.html
<form method="POST" action="" enctype='multipart/form-data'>
{% csrf_token %}
{{ form.as_p }}
<input type='submit' value='{% if submit_btn %}{{ submit_btn }}{% else %}Submit{% endif %}' />
</form>

templates/products/list_view.html
{% extends "base.html" %}

{% block style %}
h1 {
	color: green;
}
{% endblock style %}

{% block content %}


<h1>List View</h1>

{{ queryset }}

{% endblock content %}

templates/products/product_detail.html
{% extends "base.html" %}

<script>
$(document).ready(function(){
	{% block jquery %}
	$("#purchase-btn").click(function(event){
		event.preventDefault()
		var puchaseBtn = $(this)
		$("#dialog-confirm").fadeIn("300")
		$("#dialog-confirm").dialog({
			resizable: false,
			height: 350,
			width: 350,
			modal: true,
			buttons: {
				1: {
					id: "close",
					text: "Confirm",
					click: function(){
						console.log("confirm")
						var request = $.ajax({
							method: "POST",
							url: "{% url 'checkout' %}",
							data: {
								product_id: "{{ object.id }}",

							}
						})
						request.done(function(data){
							console.log(data.download)
							console.log(data.preview)
							puchaseBtn.before("<p><a href='" + data.download + "'>Download</p><p><a href='" + data.preview + "'>Preview</p>")
							puchaseBtn.fadeOut(100)

							// console.log("working...")
							// if (data.works) {
							// 	$("#content").html(data.time)
							// }
						})

						request.fail(function(jqXHR, textStatus){
							if (jqXHR.status == 404) {
								alert("Page not found!")
							} else if (jqXHR.status == 403) {
								alert("You must be logged in to do this.")
							} else {
								alert("There was an error with your request. Please try again.")
							}
						})


						$(this).dialog("close")
					},
					class: "buy-btn"
				},
				2: {
					id: "close",
					text: "Cancel",
					click: function(){
						$(this).dialog("close")
					},
					class: "cancel-btn"
				}
			}

		})
		})

	{% endblock jquery %}
	})
</script>

{% block content %}
<div class='col-primary pull-left'>
<h3>{{ object.title }}</h3><br>
{{ object.description }}<br>
<h5>{{ object.price }}</h5>
{% for img in object.thumbnail_set.all %}
	<img src="{{ img.media.url }}" />

{% endfor %}<br>
</div>
<div class='col-sidebar pull-right'>
{% if request.user.is_authenticated and object.media and object in request.user.myproducts.products.all%}
  <a href="{{object.get_download}}">download</a>
  <a href="{{object.get_download}}?preview=True">preview</a>

{% else %}
	<a id="purchase-btn" href="#">Purchase</a>
	<div id='dialog-confirm' title='Confirm Purchase' style='display:none'>
		<p>Your card on file will be charged after you agree below.</p>
	</div>
{% endif %}
<br><br>
<br>
</div>
{% endblock content%}

templates/products/product_list.html
{% extends "base.html" %}


{% block style %}

{% endblock style %}


{% block content %}
<h1>{% if vendor_name %}{{ vendor_name }} {% endif %}Products</h1>
<p>
<form method="GET" action="">
<input type='text' name='q' placeholder='Search' value='{{ request.GET.q }}'>
<input type='submit' value='Search'/>
</form>
</p>

<ul>
{% for instance in product_list %}
  <li><a href="{{ instance.get_absolute_url }}">{{ instance.title }} </a><br>
     {{ instance.description |urlize|truncatechars:100 }} <br>
     {{ instance.price }}</li>
{% endfor %}

</ul>



{% endblock %}

templates/products/product_list_snippet.html
{% load get_thumbnail %}


{% for instance in product_list %}
    <li class="">
    	<a href='{{ instance.get_absolute_url }}'>{{ instance.title }}</a><br/>
    	{% if instance|get_thumbnail:"micro" %}
    	<a href='{{ instance.get_absolute_url }}'>

    		<img src='{{ instance|get_thumbnail:"micro" }}' /></a>
            <br/>
    	{% endif %}

    	<!-- {{ instance.get_html_price|safe }} -->
   </li>
{% empty %}
    <li>No Products yet.</li>
{% endfor %}

templates/products/update_view.html
{% extends 'base.html' %}

{% block content %}
<h1>Edit product</h1>
<form class="" action="" method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit" name="button">Submit</button>
</form>

{% endblock content %}